name: CI Pipeline

on:
  push:
    branches: [main, 'feat/*']
  pull_request:
    branches: [main, 'feat/*']

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  migrate:
    uses: ./.github/workflows/migrate.yml
    needs: unit-tests
