name: Format Code

on:
  workflow_call:

jobs:
  format-code:
    name: Format code with CSharpier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore CSharpier tool
        run: dotnet tool restore

      - name: Format code
        run: dotnet csharpier .

      - name: Commit and push formatted code
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          push_options: '--force-with-lease'
          commit_message: "[Bot] Apply CSharpier updates"
          commit_author: GitHub Actions Bot <actions@github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
