name: Migrate

on:
  workflow_call:

jobs:
  migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      APPDATA: "/tmp"
      SQL_SERVER: localhost
      SQL_PORT: 1433
      SQL_DATABASE: ShoppingCartManagerDB
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_CONNECTION_STRING: "Server=${{ env.SQL_SERVER }},${{ env.SQL_PORT }};User Id=${{ env.SQL_USER }};Password=${{ env.SQL_PASSWORD }};Encrypt=false;TrustServerCertificate=true;"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ./ShoppingCartManager.sln

      - name: Build
        run: dotnet build ./ShoppingCartManager.sln --configuration Release --no-restore

      - name: Start SQL Server
        run: |
          cd ${{ github.workspace }}
          docker compose -f docker-compose.ci.yml up -d db-sqlserver
          sleep 60

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 1433; then
              echo "SQL Server is ready!"
              break
            fi
            echo "Waiting for SQL Server to be ready..."
            sleep 10
          done

      - name: Create SQL Server database if it doesn't exist
        run: |
          echo 'using Microsoft.Data.SqlClient;' > CreateDatabaseApp.cs
          echo 'class Program {' >> CreateDatabaseApp.cs
          echo '    static void Main() {' >> CreateDatabaseApp.cs
          echo "        var connectionString = \"${{ env.SQL_CONNECTION_STRING }}\";" >> CreateDatabaseApp.cs
          echo '        using (var connection = new SqlConnection(connectionString)) {' >> CreateDatabaseApp.cs
          echo "            connection.Open();" >> CreateDatabaseApp.cs
          echo "            var command = new SqlCommand(\"IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '${{ env.SQL_DATABASE }}') CREATE DATABASE [${{ env.SQL_DATABASE }}];\", connection);" >> CreateDatabaseApp.cs
          echo '            command.ExecuteNonQuery();' >> CreateDatabaseApp.cs
          echo '        }' >> CreateDatabaseApp.cs
          echo '    }' >> CreateDatabaseApp.cs
          echo '}' >> CreateDatabaseApp.cs

          dotnet add package Microsoft.Data.SqlClient
          dotnet build CreateDatabaseApp.csproj
          dotnet run

      - name: Install FluentMigrator CLI
        run: dotnet tool install --global FluentMigrator.DotNet.Cli

      - name: Apply migrations
        run: |
          dotnet fm migrate \
            -a ./src/ShoppingCartManager.Persistence/bin/Release/net9.0/ShoppingCartManager.Persistence.dll \
            -p sqlserver \
            -c "${{ env.SQL_CONNECTION_STRING }}"

      - name: Stop SQL Server
        if: always()
        run: |
          cd ${{ github.workspace }}
          docker compose -f docker-compose.ci.yml down
